### ISSUE TITLE
version 3.0.0 does not work

### ISSUE THREAD

**Issue by steeply** [gf3/moment-range#145]
```
"dependencies": {
    "async": "^2.1.4",
    "moment": "^2.17.1",
    "moment-range": "^3.0.0",
  }
"engines": {
    "node": ">=7.4.0",
    "npm": ">=4.1.1"
  },
```
```
const start = new Date(2012, 0, 15);
const end   = new Date(2012, 4, 23);
const range = moment.range(start, end);
```

```
Unhandled rejection Error: Callback was already called.
    at /Applications/MAMP/htdocs/project/node_modules/async/dist/async.js:837:32
    at /Applications/MAMP/htdocs/project/node_modules/async/dist/async.js:3691:13
    at apply (/Applications/MAMP/htdocs/project/node_modules/async/dist/async.js:21:25)
    at /Applications/MAMP/htdocs/project/node_modules/async/dist/async.js:56:12
    at /Applications/MAMP/htdocs/project/build/server.js:301:20
    at /Applications/MAMP/htdocs/project/build/server.js:1245:14
    at tryCatcher (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/MAMP/htdocs/project/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Version 2.2.0 has worked steadily on this code.

**Comment by gf3** [comment]
@steeply how are you importing moment and moment-range?

**Comment by steeply** [comment]
@gf3 

```
  var moment = require('moment');
  var momentRange = require('moment-range');
```

**Comment by steeply** [comment]
@gf3
```
> node ./build/server

{ [Function: hooks]
  momentProperties: [],
  suppressDeprecationWarnings: false,
  deprecationHandler: null,
  parseTwoDigitYear: [Function],
  createFromInputFallback: [Function],
  ISO_8601: [Function],
  updateOffset: [Function],
  defaultFormat: 'YYYY-MM-DDTHH:mm:ssZ',
  defaultFormatUtc: 'YYYY-MM-DDTHH:mm:ss[Z]',
  lang: [Function],
  langData: [Function],
  version: '2.17.1',
  fn: 
   Moment {
     add: [Function],
     calendar: [Function: calendar$1],
     clone: [Function: clone],
     diff: [Function: diff],
     endOf: [Function: endOf],
     format: [Function: format],
     from: [Function: from],
     fromNow: [Function: fromNow],
     to: [Function: to],
     toNow: [Function: toNow],
     get: [Function: stringGet],
     invalidAt: [Function: invalidAt],
     isAfter: [Function: isAfter],
     isBefore: [Function: isBefore],
     isBetween: [Function: isBetween],
     isSame: [Function: isSame],
     isSameOrAfter: [Function: isSameOrAfter],
     isSameOrBefore: [Function: isSameOrBefore],
     isValid: [Function: isValid$1],
     lang: [Function],
     locale: [Function: locale],
     localeData: [Function: localeData],
     max: [Function],
     min: [Function],
     parsingFlags: [Function: parsingFlags],
     set: [Function: stringSet],
     startOf: [Function: startOf],
     subtract: [Function],
     toArray: [Function: toArray],
     toObject: [Function: toObject],
     toDate: [Function: toDate],
     toISOString: [Function: toISOString],
     inspect: [Function: inspect],
     toJSON: [Function: toJSON],
     toString: [Function: toString],
     unix: [Function: unix],
     valueOf: [Function: valueOf],
     creationData: [Function: creationData],
     year: [Function],
     isLeapYear: [Function: getIsLeapYear],
     weekYear: [Function: getSetWeekYear],
     isoWeekYear: [Function: getSetISOWeekYear],
     quarters: [Function: getSetQuarter],
     quarter: [Function: getSetQuarter],
     month: [Function: getSetMonth],
     daysInMonth: [Function: getDaysInMonth],
     weeks: [Function: getSetWeek],
     week: [Function: getSetWeek],
     isoWeeks: [Function: getSetISOWeek],
     isoWeek: [Function: getSetISOWeek],
     weeksInYear: [Function: getWeeksInYear],
     isoWeeksInYear: [Function: getISOWeeksInYear],
     date: [Function],
     days: [Function: getSetDayOfWeek],
     day: [Function: getSetDayOfWeek],
     weekday: [Function: getSetLocaleDayOfWeek],
     isoWeekday: [Function: getSetISODayOfWeek],
     dayOfYear: [Function: getSetDayOfYear],
     hours: [Function],
     hour: [Function],
     minutes: [Function],
     minute: [Function],
     seconds: [Function],
     second: [Function],
     milliseconds: [Function],
     millisecond: [Function],
     utcOffset: [Function: getSetOffset],
     utc: [Function: setOffsetToUTC],
     local: [Function: setOffsetToLocal],
     parseZone: [Function: setOffsetToParsedOffset],
     hasAlignedHourOffset: [Function: hasAlignedHourOffset],
     isDST: [Function: isDaylightSavingTime],
     isLocal: [Function: isLocal],
     isUtcOffset: [Function: isUtcOffset],
     isUtc: [Function: isUtc],
     isUTC: [Function: isUtc],
     zoneAbbr: [Function: getZoneAbbr],
     zoneName: [Function: getZoneName],
     dates: [Function],
     months: [Function],
     years: [Function],
     zone: [Function],
     isDSTShifted: [Function],
     range: { [Function: range] constructor: [Function: DateRange] },
     within: [Function] },
  min: [Function: min],
  max: [Function: max],
  now: [Function: now],
  utc: [Function: createUTC],
  unix: [Function: createUnix],
  months: [Function: listMonths],
  isDate: [Function: isDate],
  locale: [Function: getSetGlobalLocale],
  invalid: [Function: createInvalid],
  duration: 
   { [Function: createDuration]
     fn: 
      { [Number: NaN]
        abs: [Function: abs],
        add: [Function: add$1],
        subtract: [Function: subtract$1],
        as: [Function: as],
        asMilliseconds: [Function],
        asSeconds: [Function],
        asMinutes: [Function],
        asHours: [Function],
        asDays: [Function],
        asWeeks: [Function],
        asMonths: [Function],
        asYears: [Function],
        valueOf: [Function: valueOf$1],
        _bubble: [Function: bubble],
        get: [Function: get$2],
        milliseconds: [Function],
        seconds: [Function],
        minutes: [Function],
        hours: [Function],
        days: [Function],
        weeks: [Function: weeks],
        months: [Function],
        years: [Function],
        humanize: [Function: humanize],
        toISOString: [Function: toISOString$1],
        toString: [Function: toISOString$1],
        toJSON: [Function: toISOString$1],
        locale: [Function: locale],
        localeData: [Function: localeData],
        toIsoString: [Function],
        lang: [Function] } },
  isMoment: [Function: isMoment],
  weekdays: [Function: listWeekdays],
  parseZone: [Function: createInZone],
  localeData: [Function: getLocale],
  isDuration: [Function: isDuration],
  monthsShort: [Function: listMonthsShort],
  weekdaysMin: [Function: listWeekdaysMin],
  defineLocale: [Function: defineLocale],
  updateLocale: [Function: updateLocale],
  locales: [Function: listLocales],
  weekdaysShort: [Function: listWeekdaysShort],
  normalizeUnits: [Function: normalizeUnits],
  relativeTimeRounding: [Function: getSetRelativeTimeRounding],
  relativeTimeThreshold: [Function: getSetRelativeTimeThreshold],
  calendarFormat: [Function: getCalendarFormat],
  range: { [Function: range] constructor: [Function: DateRange] } }

```

**Comment by gf3** [comment]
<img width="553" alt="screen shot 2017-01-30 at 11 28 49 am" src="https://cloud.githubusercontent.com/assets/18397/22431375/51522bb4-e6df-11e6-85e7-3eb9e9c72737.png">

**Comment by steeply** [comment]
@gf3

```
      start = new Date(2012, 0, 15);
      end = new Date(2012, 4, 23);
      momentRange.extendMoment(moment);
      range = moment.range(start, end);
      console.log(range);

{ [Number: 11145600000]
  start: moment("2012-01-15T00:00:00.000"),
  end: moment("2012-05-23T00:00:00.000") }

```

It worked. Thank you!

**Comment by gf3** [comment]
@steeply glad i could help!
